-- TimeShift: close the public-schema exposure on this Supabase project.
--
-- Paste this whole file into the SQL Editor and run it. Safe to run twice, and
-- safe to run on a project that is already fixed. Everything is in one
-- transaction: if any statement fails, nothing is applied.
--
-- Generated by scripts/generate-supabase-sql.mjs from the migrations themselves.
-- It applies exactly what `prisma migrate deploy` would, and records the same
-- migration history, so the CLI stays consistent with the database afterwards.

BEGIN;

-- Precondition. This file carries the lockdown migrations only, not the whole
-- schema, so it assumes the project has already been migrated up to that point.
-- Without this check the first ALTER TABLE fails, every following statement
-- reports "current transaction is aborted", and the operator has to read a wall
-- of cascade noise to find the one sentence that matters. Nothing is applied
-- either way -- the transaction is what guarantees that -- this just says why.
DO $$
BEGIN
  IF to_regclass('public."User"') IS NULL THEN
    RAISE EXCEPTION 'This project has no TimeShift schema yet, so there is nothing to lock down. This file carries the lockdown migrations only. Apply the earlier migrations first (prisma migrate deploy), then run this again. Nothing has been changed.';
  END IF;
END
$$;


-- ===========================================================================
-- 20260818204500_lock_down_public_schema
-- ===========================================================================
-- Lock the public schema away from Supabase's PostgREST roles.
--
-- Why this migration exists
-- ------------------------
-- TimeShift reaches Postgres only through Prisma over DATABASE_URL; it uses no
-- Supabase SDK (AGENTS.md §5). Supabase, however, still publishes every table in
-- the `public` schema through PostgREST, and its bootstrap grants ALL on new
-- tables in `public` to the `anon` and `authenticated` roles. `anon` is the role
-- behind a project's publishable key, so until this migration every table Prisma
-- created was world-readable and world-writable over HTTPS:
--
--   * "Session"."token"    -- live session cookies -> sign in as any user
--   * "LoginToken"."token" -- unconsumed magic links -> take over any account
--   * "User"."email"       -- the whole user list
--
-- That is what the Supabase advisories `rls_disabled_in_public` and
-- `sensitive_columns_exposed` flagged. Prisma does not model RLS or grants, so
-- neither is expressible in schema.prisma and both have to live here.
--
-- The fix is two independent layers; either alone would close the hole.
--   1. Row-Level Security on every table, with NO policies -> deny-all for every
--      role except the table owner. The owner (the `postgres` role Prisma
--      migrates and connects as) bypasses RLS, so the app is unaffected. FORCE
--      ROW LEVEL SECURITY is deliberately NOT set: that would lock out the
--      application's own connection.
--   2. Revoking the table grants PostgREST rides on, so the tables disappear
--      from the API surface entirely rather than merely returning zero rows.
--
-- `service_role` is intentionally left alone: it is reachable only with the
-- secret service key, never ships to a browser, and carries BYPASSRLS by design.
--
-- On guards, precisely: block 2 is role-guarded and so is a true no-op on a plain
-- local/CI Postgres where the Supabase roles do not exist, and blocks 1b and 2
-- are ownership-guarded so neither can abort on a table this role does not own.
-- Block 1a is NOT conditional -- those six statements enable RLS on every
-- database the migration touches, local ones included. That is safe only because
-- the app connects as the table owner, who bypasses RLS. Point a local
-- DATABASE_URL at a non-owner role and every query returns zero rows silently,
-- with no error to explain it; that is the one failure mode worth knowing about.

-- 1a. RLS on each modelled table. These lines are contract-tested against
--     schema.prisma by security-rls.test.ts: adding a model without adding its
--     line here fails CI.
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LoginToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Trip" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FlightSegment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FlightQueryCache" ENABLE ROW LEVEL SECURITY;

-- 1b. Safety net for anything in `public` that schema.prisma does not model --
--     notably Prisma's own `_prisma_migrations` bookkeeping table, which is
--     equally exposed and leaks the schema history.
--
--     The pg_has_role guard is load-bearing: ALTER TABLE requires ownership, so a
--     table in `public` owned by another role (an extension installed there, or
--     anything created by another tool) would raise `must be owner of table`,
--     abort the migration, and leave Prisma's history wedged on a live database.
--     Tables that fail the guard are skipped because they could never have been
--     altered from here anyway; they are not Prisma's and hold none of our data.
DO $$
DECLARE t regclass;
BEGIN
  FOR t IN
    SELECT c.oid::regclass
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND c.relkind = 'r' AND NOT c.relrowsecurity
      AND pg_catalog.pg_has_role(current_user, c.relowner, 'USAGE')
  LOOP
    EXECUTE format('ALTER TABLE %s ENABLE ROW LEVEL SECURITY', t);
  END LOOP;
END
$$;

-- 2. Drop the PostgREST-facing grants, now and for every table Prisma creates
--    later. Without the ALTER DEFAULT PRIVILEGES half, the next `prisma migrate`
--    would silently hand `anon` a fresh publicly-readable table.
DO $$
DECLARE r text; obj record;
BEGIN
  FOREACH r IN ARRAY ARRAY['anon', 'authenticated'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
      -- Per-object and ownership-guarded, for the same reason block 1b is: the
      -- blanket `REVOKE ALL ON ALL TABLES IN SCHEMA public` aborts with
      -- `permission denied for table ...` on the first object the migrating role
      -- does not own, which would fail the migration on a live database. Objects
      -- that fail the guard are not ours and were never granted by us.
      FOR obj IN
        SELECT c.oid::regclass AS ident, c.relkind AS kind
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public'
          AND c.relkind IN ('r', 'p', 'v', 'm', 'f', 'S')
          AND pg_catalog.pg_has_role(current_user, c.relowner, 'USAGE')
      LOOP
        IF obj.kind = 'S' THEN
          EXECUTE format('REVOKE ALL ON SEQUENCE %s FROM %I', obj.ident, r);
        ELSE
          EXECUTE format('REVOKE ALL ON TABLE %s FROM %I', obj.ident, r);
        END IF;
      END LOOP;
      -- Removes the role's DIRECT schema grant only. `anon` still holds USAGE
      -- on `public` through the PUBLIC pseudo-role, which Postgres grants by
      -- default (PG15 revoked CREATE from PUBLIC; USAGE stayed). So this line is
      -- belt-and-braces, not load-bearing -- the table-level revoke below and
      -- the RLS above are what actually close the door. Revoking USAGE from
      -- PUBLIC outright would shut it fully but has a far wider blast radius
      -- across Supabase's own roles; that is an owner decision (AGENTS.md §11).
      EXECUTE format('REVOKE ALL ON SCHEMA public FROM %I', r);
      EXECUTE format(
        'ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM %I', r);
      EXECUTE format(
        'ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM %I', r);
    END IF;
  END LOOP;
END
$$;

-- Record it the way `prisma migrate deploy` would, so the CLI does not try to
-- apply it again later.
INSERT INTO "_prisma_migrations"
  ("id", "checksum", "finished_at", "migration_name", "logs", "rolled_back_at", "started_at", "applied_steps_count")
SELECT gen_random_uuid()::text, '136eb5b43438ce48fec629e00ccec0ef6a98d5b1f1f219910c16b592191c9ae5', now(), '20260818204500_lock_down_public_schema', NULL, NULL, now(), 1
WHERE NOT EXISTS (
  SELECT 1 FROM "_prisma_migrations" WHERE "migration_name" = '20260818204500_lock_down_public_schema'
);


-- ===========================================================================
-- 20260818211531_add_rate_limit
-- ===========================================================================
-- CreateTable
CREATE TABLE IF NOT EXISTS "RateLimit" (
    "key" TEXT NOT NULL,
    "count" INTEGER NOT NULL DEFAULT 0,
    "expiresAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RateLimit_pkey" PRIMARY KEY ("key")
);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "RateLimit_expiresAt_idx" ON "RateLimit"("expiresAt");

-- Same lockdown as every other table in `public` (see
-- 20260818204500_lock_down_public_schema). A new table would otherwise be
-- published through PostgREST; the default-privileges revoke from that migration
-- already denies `anon` the grants, but RLS is the other half and does not apply
-- itself to tables created later. security-rls.test.ts enforces this line.
ALTER TABLE "RateLimit" ENABLE ROW LEVEL SECURITY;

-- Record it the way `prisma migrate deploy` would, so the CLI does not try to
-- apply it again later.
INSERT INTO "_prisma_migrations"
  ("id", "checksum", "finished_at", "migration_name", "logs", "rolled_back_at", "started_at", "applied_steps_count")
SELECT gen_random_uuid()::text, '8caf70cb1fc24d71e33a8d3b65ddabb4b659eb7caf2551127f647392995173bc', now(), '20260818211531_add_rate_limit', NULL, NULL, now(), 1
WHERE NOT EXISTS (
  SELECT 1 FROM "_prisma_migrations" WHERE "migration_name" = '20260818211531_add_rate_limit'
);


-- ===========================================================================
-- 20260818212336_drop_dead_password_hash
-- ===========================================================================
/*
  Drop the dead `User.passwordHash` column.

  Sign-in moved to passwordless magic links, and nothing has read or written this
  column since: the only references left in the repo were this schema line, the
  historical migrations that created it, and a spec paragraph. The account row is
  created by `app/api/auth/verify` without it, and no code path consults it.

  It still held real bcrypt hashes from before that move, which is what Supabase's
  `sensitive_columns_exposed` advisory pointed at. The lockdown migration
  (20260818204500) made the column unreachable; this removes it, because
  credentials nothing reads should not be retained at all.

  Deliberately a SEPARATE migration from the lockdown: dropping a column cannot be
  undone, and the two Supabase projects are migrated by hand. Bundling it would
  have forced an irreversible change into the same `prisma migrate deploy` run as
  an urgent security fix. The lockdown must be applicable on its own.

  Warning kept from the generator, because it is the point: the data in this
  column is lost when this runs.
*/
-- AlterTable
ALTER TABLE "User" DROP COLUMN IF EXISTS "passwordHash";

-- Record it the way `prisma migrate deploy` would, so the CLI does not try to
-- apply it again later.
INSERT INTO "_prisma_migrations"
  ("id", "checksum", "finished_at", "migration_name", "logs", "rolled_back_at", "started_at", "applied_steps_count")
SELECT gen_random_uuid()::text, '039dcc0bb2cf329b3b5ee5cf16f0e086a34f9bab0de1fa48a34cdffde4061791', now(), '20260818212336_drop_dead_password_hash', NULL, NULL, now(), 1
WHERE NOT EXISTS (
  SELECT 1 FROM "_prisma_migrations" WHERE "migration_name" = '20260818212336_drop_dead_password_hash'
);


-- ===========================================================================
-- 20260818233000_revoke_default_privileges_all_classes
-- ===========================================================================
-- Finish the default-privileges half of the public-schema lockdown.
--
-- `20260818204500_lock_down_public_schema` revoked default privileges on TABLES
-- and SEQUENCES. `pg_default_acl` holds one row per (role, schema, object
-- class), and Supabase's bootstrap also grants defaults on FUNCTIONS -- so that
-- row survived the lockdown. Two consequences, one of each kind:
--
--   Security: the surviving entry means the next function created in `public`
--   by the migrating role is granted EXECUTE to `anon`, and PostgREST publishes
--   a `public` function as an RPC endpoint. No such function exists today; the
--   point of a default-privileges revoke is precisely the object that does not
--   exist yet.
--
--   Operational: `scripts/verify-lockdown.mjs` and the verification query in
--   `docs/supabase-lockdown.sql` both read `pg_default_acl` for `anon` and
--   `authenticated` without filtering by object class. The FUNCTIONS row made a
--   fully locked-down database report a problem, which `secure-database.sh`
--   turns into a hard failure -- skipping the credential rotation that is part
--   of the fix. Revoking the whole surface is what makes those checks true,
--   rather than narrowing the checks to match a partial revoke.
--
-- TYPES is included for the same reason TABLES and SEQUENCES are: it is a class
-- `pg_default_acl` can hold in a schema, so leaving it out leaves a row the
-- verifiers would flag. Object class 'n' (schemas) is stored with no namespace
-- and so is never reached by an `IN SCHEMA public` sweep.
--
-- Same shape as the original: guarded on the role existing, and issued through
-- `format`/`%I` per role. `ALTER DEFAULT PRIVILEGES` only ever alters entries
-- owned by the role running it -- Supabase's own `supabase_admin` entries are
-- untouched here and remain harmless, because a default-ACL entry governs only
-- the objects its owner creates, and migrations do not run as that role.
-- Spelled out one class per statement rather than looped over a class array:
-- the set of classes covered is the whole point of this migration, and
-- security-rls.test.ts asserts each one by name so a future class cannot be
-- dropped from the sweep without CI saying so.
DO $$
DECLARE r text;
BEGIN
  FOREACH r IN ARRAY ARRAY['anon', 'authenticated'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
      EXECUTE format(
        'ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM %I', r);
      EXECUTE format(
        'ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM %I', r);
      EXECUTE format(
        'ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON FUNCTIONS FROM %I', r);
      EXECUTE format(
        'ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TYPES FROM %I', r);
    END IF;
  END LOOP;
END
$$;

-- Record it the way `prisma migrate deploy` would, so the CLI does not try to
-- apply it again later.
INSERT INTO "_prisma_migrations"
  ("id", "checksum", "finished_at", "migration_name", "logs", "rolled_back_at", "started_at", "applied_steps_count")
SELECT gen_random_uuid()::text, '7233dab722d697a3650d63c56c1ad8c193e35b05fdf66e90dcc09e976666dd99', now(), '20260818233000_revoke_default_privileges_all_classes', NULL, NULL, now(), 1
WHERE NOT EXISTS (
  SELECT 1 FROM "_prisma_migrations" WHERE "migration_name" = '20260818233000_revoke_default_privileges_all_classes'
);


-- ===========================================================================
-- Rotate the credentials the exposure made readable
-- ===========================================================================
-- Session tokens and unconsumed magic links were readable by anyone holding this
-- project's publishable key, and both are bearer credentials with no second
-- factor. Expiring rather than deleting keeps the history and is safe to repeat.
-- Everyone signs in again as normal.
UPDATE "Session"    SET "expiresAt" = now() WHERE "expiresAt" > now();
UPDATE "LoginToken" SET "usedAt"    = now() WHERE "usedAt" IS NULL;

COMMIT;

-- ===========================================================================
-- Verification -- one query, one result grid, every row must say OK
-- ===========================================================================
-- The SQL Editor only renders the LAST statement's results, so the whole verdict
-- is folded into a single query rather than split across two.
--
-- Row 1 covers what exists today, checked across the same surface the migration
-- revokes -- all four read/write privileges, and views, materialized views and
-- sequences as well as tables -- because a role holding only INSERT, or a view
-- over "User", is exposure a SELECT-on-tables check reports as clean.
--
-- The remaining rows cover the half that regresses silently: default privileges
-- decide what the NEXT object created gets, whatever today's objects say. There
-- is one row per (role, object class), so several are normal. A default-ACL entry
-- only governs objects created by its owner, so Supabase's own internal entries
-- are expected and harmless -- they never govern an object your migrations make.
-- These rows may be absent entirely, which is also fine: a one-row grid saying OK
-- is a pass, not a truncated result.
WITH obj AS (
  SELECT CASE WHEN c.relkind IN ('r','p') AND NOT c.relrowsecurity THEN false ELSE true END AS rls_ok,
         NOT (COALESCE(has_table_privilege('anon', c.oid, 'SELECT'), false)
           OR COALESCE(has_table_privilege('anon', c.oid, 'INSERT'), false)
           OR COALESCE(has_table_privilege('anon', c.oid, 'UPDATE'), false)
           OR COALESCE(has_table_privilege('anon', c.oid, 'DELETE'), false)
           OR COALESCE(has_table_privilege('authenticated', c.oid, 'SELECT'), false)
           OR COALESCE(has_table_privilege('authenticated', c.oid, 'INSERT'), false)
           OR COALESCE(has_table_privilege('authenticated', c.oid, 'UPDATE'), false)
           OR COALESCE(has_table_privilege('authenticated', c.oid, 'DELETE'), false)) AS no_api_access
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public' AND c.relkind IN ('r','p','v','m','f','S')
)
SELECT 1                                                       AS ord,
       'existing objects'                                      AS "check",
       count(*)::text || ' object(s) in public'                AS detail,
       CASE WHEN count(*) FILTER (WHERE NOT no_api_access) > 0
              THEN 'PROBLEM - ' || count(*) FILTER (WHERE NOT no_api_access)::text
                   || ' reachable with the publishable key'
            WHEN count(*) FILTER (WHERE NOT rls_ok) > 0
              THEN 'PROBLEM - ' || count(*) FILTER (WHERE NOT rls_ok)::text
                   || ' table(s) without RLS'
            ELSE 'OK' END                                      AS verdict
FROM obj
UNION ALL
SELECT 2,
       'future objects',
       'default privileges on ' || CASE d.defaclobjtype
              WHEN 'r' THEN 'tables'    WHEN 'S' THEN 'sequences'
              WHEN 'f' THEN 'functions' WHEN 'T' THEN 'types'
              ELSE d.defaclobjtype::text END
         || ' owned by ' || pg_get_userbyid(d.defaclrole)
         || ' grant ' || string_agg(DISTINCT r.rolname, ' + '),
       CASE WHEN pg_get_userbyid(d.defaclrole) = current_user
            THEN 'PROBLEM - governs the objects your migrations create'
            ELSE 'OK - Supabase internal role, never governs your objects' END
FROM pg_default_acl d
JOIN pg_namespace n ON n.oid = d.defaclnamespace
CROSS JOIN LATERAL aclexplode(d.defaclacl) a
JOIN pg_roles r ON r.oid = a.grantee
WHERE n.nspname = 'public' AND r.rolname IN ('anon', 'authenticated')
GROUP BY d.defaclrole, d.defaclobjtype
ORDER BY 1;
